### ISSUE TITLE
Implement review functionality

### ISSUE THREAD

**Issue by tkomiya24** [tkomiya24/hobby_site#29]
Users should be able to review other users based on their instrument/role/etc.

**Comment by tkomiya24** [comment]
- Refactor all the instrument models so that they can be linked to by Users through one polymorphic field
  - [x] Drummer #37 
  - [x] Singer #42 
  - [x] Bassist #43
  - [x] Guitarist #45 
- Fix the views so they can display and create them properly
  - [x] Drummer #38 
  - [x] Singer #42 
  - [x] Bassist #43 
  - [x] Guitarist #45 
- [x] Remove form instrument form partial #48 
- [ ] Restrict model so that a User can only be associated with each instrument once
- [x] Fix method that checks if a user is a musician #49 
- [x] Fix the review relation to be associated with 'reviewable'. #50

**Comment by tkomiya24** [comment]
Blocked by #52. Can't review a user if you can't see any other ones!

**Comment by tkomiya24** [comment]
No longer blocked
